In [1]:
import numpy as np

In [3]:
# creating an array

a = np.array([1,2,3,4])

In [5]:
type(a) # n-dimensional array

numpy.ndarray

In [10]:
# Providing data types to arrays
a = np.array([1,2,3,4], dtype = float)
print(a)

[1. 2. 3. 4.]


In [9]:
a = np.array([1,2,3,4], dtype = str)
print(a)

['1' '2' '3' '4']


In [14]:
b = np.array([[1,2,3],[4,5,6]]) # 2-dimensional array
print(b)

[[1 2 3]
 [4 5 6]]


In [13]:
len(b)

2

In [37]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]]) # 2-dimensional array
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
c.ndim # how many dimensions?

2

In [31]:
a.ndim

1

In [ ]:
# Dimension in numpy comes from how many axes it has like when we say [[1,2,3],[4,5,6]], this has columns and rows. Similarly, when we say:
#[[1,2,3],[4,5,6],[7,8,9]], this also has rows and columns so they both are 2-dimensional. However, when we say:

'''
[
[[1,2,4],[4,5,6]]
[[7,8,9],[10,11,12]]
]

This is like stacking tables, similar to like having multiple spreadsheets. We have our rows and columns but we have two of them now.
''' 

In [33]:
# shape of a numpy array

a.shape

(4,)

In [34]:
b.shape

(2, 3)

In [35]:
c.shape

(3, 3)

In [39]:
c.dtype # data type

dtype('int64')

In [41]:
# Fetching elements 
a = np.array([[1,2,3],[4,5,6]])

a[0,1]

np.int64(2)

In [43]:
# entire row
a[0,:]

array([1, 2, 3])

In [44]:
a[:,1]

array([2, 5])

In [45]:
# accessing and changing values of numpy array

a[0,1] = 100
print(a)

[[  1 100   3]
 [  4   5   6]]


# Zeros and ones method in numpy

In [ ]:
z = np.zeros((2,3))  # rows and columns are arguments
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [55]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
np.ones((2,3), dtype=str)

array([['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [57]:
np.full((3,3),10, dtype=str)

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [62]:
# using random with numpy

# Creating a random float array
print("Random array of float values:")
print(np.random.rand(3,3), "\n")

# Creating a random integer array
print("Random array of integer values:")
print(np.random.randint(1,4, size = (3,3)))

Random array of float values:
[[8.64460510e-01 9.97869846e-01 3.24014942e-01]
 [5.72501748e-01 4.13735282e-01 2.13600684e-01]
 [4.86096041e-01 6.28073809e-01 4.37884837e-04]] 

Random array of integer values:
[[1 3 1]
 [1 1 2]
 [1 3 2]]


In [63]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Arithmetic Operations with NumPy

In [65]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [66]:
a + 2

array([3, 4, 5, 6])

In [67]:
a.min()

np.int64(1)

In [68]:
a.max()

np.int64(4)

In [69]:
np.min(a)

np.int64(1)

In [70]:
np.max(a)

np.int64(4)

In [71]:
np.mean(a)

np.float64(2.5)

In [72]:
np.sum(a)

np.int64(10)